export const REGISTER = "/api/Identity/register"
export const LOGIN = "/api/Identity/login"
export const CURRENT_USER = "/api/Identity/current-user"
export const DELETE_USER = "/api/Identity/user"
export const GET_USER = "/api/Identity/user"
export const USER_ROLE = "/api/Identity/userRole"